// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOcRt-6qk4pHhn_fE8MnX8PcTTcRaiOk',
    appId: '1:563760218264:web:b3d3fedaea82f0d28b50ed',
    messagingSenderId: '563760218264',
    projectId: 'comp3130-quiz',
    authDomain: 'comp3130-quiz.firebaseapp.com',
    storageBucket: 'comp3130-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA691YBsOa8af1RUGoGJLxCk5b8Ak_lXmA',
    appId: '1:563760218264:android:d8f4647ec9cf047b8b50ed',
    messagingSenderId: '563760218264',
    projectId: 'comp3130-quiz',
    storageBucket: 'comp3130-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8jrrostTxHZpLsyKvdokswaTbhlN324s',
    appId: '1:563760218264:ios:76e1c368bbd9ca188b50ed',
    messagingSenderId: '563760218264',
    projectId: 'comp3130-quiz',
    storageBucket: 'comp3130-quiz.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );
}
